version: 3,7

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: "no"
    environment:
      DB_HOST: "localhost"
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - fourrum

  backend:
    container_name: backend
    depends_on: 
      - mysql
    build:
      context: "./backend"
    restart: "no"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      JWT_KEY: ${JWT_KEY}
    ports:
      - '${BACKEND_PORT}:8000'
    volumes:
      - ./backend:/opt
    networks:
      - fourrum

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: "./frontend"
  #   restart: always
  #   ports:
  #     - '19006:19006'
  #     - '19001:19001'
  #     - '19002:19002'
  #   volumes:
  #     - ./frontend:/var/www/html
  #   networks:
  #     - fourrum


volumes:
  mysql:
    driver: local
    
networks:
  fourrum: {}