version: 3,7

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      DB_HOST: "localhost"
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - fourrum

  backend:
    container_name: backend
    build:
      context: "./backend"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_KEY: ${JWT_KEY}
    ports:
      - '${BACKEND_PORT}:8000'
    volumes:
      - ./backend:/opt
    networks:
      - fourrum

  frontend:
    container_name: frontend
    build:
      context: "./frontend"
    restart: always
    ports:
      - '19006:19006'
    volumes:
      - ./frontend:/var/www/html
    networks:
      - fourrum


volumes:
  mysql:
    driver: local
    
networks:
  fourrum: {}